project_id = "bwfnxidpifugpklczfyo"

[functions.send-invite-email]
verify_jwt = false

[functions.bunny-ops]
verify_jwt = false

[functions.deliverables-ops]
verify_jwt = false

[functions.presigned-upload]
verify_jwt = false

[functions.delete-asset]
verify_jwt = false
